default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: bookmarkd_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: bookmarkt_test
  host: localhost
  username: postgres
  password: password

production:
  <<: *default
  database: bookmarkp_production
  username: postgres
  password: password

staging:
  <<: *default
  database: bookmarks_de1velopment
  host: localhost
  username: postgres
  password: password