default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: up_work_development



production:
  <<: *default
  database: up_work_test_staging
